### PR TITLE
Misc fixes

### LINKED ISSUE #225: Fix: Remove Companies from Backend and Frontend

### PR DESCRIPTION
**Pull request by malindesire**
**Reason for change**

This PR aims to clean up demo material "companies" from frontend and backend, set NotFoundPage as errorElement on dynamic routes and sort modules on the course page.

**Changes**

- Removed companies feature and imports from frontend.
- Updated project name in package.json.
- Removed company demo files from backend.
- Added NotFoundPage as errorElement on our dynamic routes.
- Added sorting function to modules on CoursePage.

**How to test**

1. Run `npm install` and then start the project.
2. Make sure there are no errors and everything related to companies demo material is removed.
3. If you navigate to a page with the wrong course or module id you should get to the NotFoundPage.
4. Make sure modules on Course page are sorted by start date.

### CODE REVIEW

File: Frontend/src/main.tsx [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import './styles/index.css';
```
Comment (wpplng) [inline Frontend/src/main.tsx:1]: Behöver vi ha kvar den här filen? Eller kan vi ta bort hela mappen för features?

**Review by wpplng — APPROVED** [review]
awesome ⭐️
